/* ============================================================
   Sync the shared page shell
   ------------------------------------------------------------
   Every page repeats the same three things: the pre-paint theme
   bootstrap, the script list and (on poem pages) the `../` prefix.
   Rather than hand-editing thirty-two files, run this after changing
   the THEMES list in script.js or adding a script to the shell.

       node scripts/sync-shell.mjs          # apply
       node scripts/sync-shell.mjs --check  # report only, exit 1 on drift

   The bootstrap is generated from THEMES in script.js, so the
   whitelist a browser validates against can never fall out of step
   with the themes the site actually ships.
   ============================================================ */

import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.includes("--check");

/* ---- Read the theme registry out of script.js ---- */

const script = fs.readFileSync(path.join(ROOT, "script.js"), "utf8");
const themesBlock = script.match(/const THEMES = \[([\s\S]*?)\n\];/);
if (!themesBlock) {
  console.error("Could not find the THEMES array in script.js");
  process.exit(1);
}

const THEMES = [...themesBlock[1].matchAll(/id:\s*"([^"]+)",\s*mode:\s*"(day|night)"/g)].map(
  ([, id, mode]) => ({ id, mode })
);

if (THEMES.length < 2) {
  console.error("THEMES in script.js looks empty — not touching the pages");
  process.exit(1);
}

const DARK = new Set(THEMES.filter((theme) => theme.mode === "night").map((theme) => theme.id));

/* What the bootstrap falls back to when a reader has no stored
   preference — the first dark theme and the first light one, so the
   generated script never has to hardcode "night" and "day". */
const fallbackDark = THEMES.find((theme) => DARK.has(theme.id))?.id ?? "night";
const fallbackLight = THEMES.find((theme) => !DARK.has(theme.id))?.id ?? "day";

/* ---- The templates ---- */

const bootstrap = `  <script>
    /* Set theme + language before first paint to avoid a flash.
       Generated by scripts/sync-shell.mjs — edit THEMES in script.js
       and re-run it rather than editing thirty-two copies by hand. */
    (function () {
      try {
        var T = ${JSON.stringify(THEMES.map((theme) => theme.id))};
        var D = ${JSON.stringify([...DARK])};
        var t = localStorage.getItem("kesar_tarang_theme");
        if (T.indexOf(t) < 0) {
          t = window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches
            ? ${JSON.stringify(fallbackDark)}
            : ${JSON.stringify(fallbackLight)};
        }
        document.documentElement.dataset.theme = t;
        document.documentElement.dataset.mode = D.indexOf(t) < 0 ? "day" : "night";
        var l = localStorage.getItem("kesar_tarang_language");
        if (l === "hi" || l === "en" || l === "mr") document.documentElement.dataset.lang = l;
      } catch (e) {}
    })();
  </script>`;

const SCRIPT_TAGS = [
  '<script src="ai-config.js"></script>',
  '<script src="translations.js"></script>',
  '<script src="script.js"></script>',
  '<script src="agent.js"></script>',
];

/* ---- Walk every page ---- */

const pages = ["index.html", "bio.html", ...fs.readdirSync(path.join(ROOT, "poems"))
  .filter((file) => file.endsWith(".html"))
  .sort()
  .map((file) => path.join("poems", file))];

let changed = 0;
const drifted = [];

for (const relative of pages) {
  const file = path.join(ROOT, relative);
  const before = fs.readFileSync(file, "utf8");
  const depth = path.dirname(relative);
  const prefix = depth === "." ? "" : "../";
  /* These pages were authored on Windows and carry CRLF. Inserting LF
     into them would make every run rewrite the file again, so the
     template is written in whatever the file already uses. */
  const eol = before.includes("\r\n") ? "\r\n" : "\n";
  let html = before;

  /* 1. The pre-paint bootstrap, replaced wholesale so it always
        matches the generated template. The pattern tolerates CRLF so
        the same file is rewritten identically on every run. */
  html = html.replace(
    / {2}<script>\r?\n(?:.|\n)*?<\/script>\r?\n<\/head>/,
    `${bootstrap.replace(/\n/g, eol)}\r\n</head>`
  );

  /* 2. The script list, in order, with the right relative prefix. */
  const scripts = SCRIPT_TAGS.map(
    (tag) => `  <script src="${prefix}${tag.match(/src="([^"]+)"/)[1]}"></script>`
  ).join(eol);
  html = html.replace(
    / {2}<script src="[^"]*"><\/script>(?:\r?\n {2}<script src="[^"]*"><\/script>)*/,
    scripts
  );

  if (html !== before) {
    drifted.push(relative);
    if (!checkOnly) fs.writeFileSync(file, html, "utf8");
    changed++;
  }
}

if (checkOnly) {
  if (drifted.length) {
    console.log(`shell out of date in ${drifted.length} page(s):`);
    for (const page of drifted) console.log(`  ${page}`);
    console.log("\nrun: node scripts/sync-shell.mjs");
    process.exit(1);
  }
  console.log(`shell is in sync across ${pages.length} pages`);
} else {
  console.log(`themes: ${THEMES.length} (${DARK.size} night) · pages updated: ${changed}/${pages.length}`);
}
